version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
volumes:
  postgres:
    name: nest-db